/** Auto-generated from public/project-gallery — real client project photography */
export const PROJECT_GALLERY = {
  "additions": [
    "/project-gallery/additions/addition-1.webp",
    "/project-gallery/additions/addition-2.webp",
    "/project-gallery/additions/addition-3.jpg",
    "/project-gallery/additions/addition-4.jpg",
    "/project-gallery/additions/home-additions1.webp",
    "/project-gallery/additions/home-additions2.webp",
    "/project-gallery/additions/home-addtions2.jpg",
    "/project-gallery/additions/home-addtions3.jpg",
  ],
  "bathroom": [
    "/project-gallery/bathroom/bathroom1.jpg",
    "/project-gallery/bathroom/bathroom-1.jpg",
    "/project-gallery/bathroom/bathroom10.jpg",
    "/project-gallery/bathroom/bathroom-10.jpg",
    "/project-gallery/bathroom/bathroom12.jpg",
    "/project-gallery/bathroom/bathroom-12.jpg",
    "/project-gallery/bathroom/bathroom2.jpg",
    "/project-gallery/bathroom/bathroom-2.jpg",
    "/project-gallery/bathroom/bathroom3.jpg",
    "/project-gallery/bathroom/bathroom-3.jpg",
    "/project-gallery/bathroom/bathroom4.jpg",
    "/project-gallery/bathroom/bathroom-4.jpg",
    "/project-gallery/bathroom/bathroom5.jpg",
    "/project-gallery/bathroom/bathroom-5.jpg",
    "/project-gallery/bathroom/bathroom6.jpg",
    "/project-gallery/bathroom/bathroom-6.jpg",
    "/project-gallery/bathroom/bathroom7.jpg",
    "/project-gallery/bathroom/bathroom-7.jpg",
    "/project-gallery/bathroom/bathroom8.jpg",
    "/project-gallery/bathroom/bathroom-8.jpg",
    "/project-gallery/bathroom/bathroom9.jpg",
    "/project-gallery/bathroom/bathroom-9.jpg",
  ],
  "cabinetry": [
    "/project-gallery/cabinetry/cabinetry-1.webp",
    "/project-gallery/cabinetry/cabinetry-2.webp",
    "/project-gallery/cabinetry/cabinetry-3.webp",
    "/project-gallery/cabinetry/cabinetry-4.jpg",
    "/project-gallery/cabinetry/custom-cabinetery3.webp",
    "/project-gallery/cabinetry/custom-cabinetry1.webp",
    "/project-gallery/cabinetry/custom-cabinetry2.webp",
    "/project-gallery/cabinetry/custom-cabinetry4.jpg",
  ],
  "deck": [
    "/project-gallery/deck/deck-1.jpg",
    "/project-gallery/deck/deck-2.jpg",
    "/project-gallery/deck/deck-3.jpg",
    "/project-gallery/deck/deck-4.jpg",
    "/project-gallery/deck/deck-5.webp",
    "/project-gallery/deck/newdeckconstruction1.jpg",
    "/project-gallery/deck/newdeckconstruction2.jpg",
    "/project-gallery/deck/newdeckconstruction3.jpg",
    "/project-gallery/deck/newdeckconstruction4.jpg",
    "/project-gallery/deck/newdeckconstruction4.webp",
  ],
  "docks": [
    "/project-gallery/docks/customdock1.avif",
    "/project-gallery/docks/customdock1.jpg",
    "/project-gallery/docks/customdock2.webp",
    "/project-gallery/docks/customdock3.webp",
    "/project-gallery/docks/customdock4.jpg",
    "/project-gallery/docks/dock-1.webp",
    "/project-gallery/docks/dock-2.webp",
    "/project-gallery/docks/dock-3.jpg",
    "/project-gallery/docks/dock-4.jpg",
  ],
  "interiors": [
    "/project-gallery/interiors/bedroom1.jpg",
    "/project-gallery/interiors/bedroom2.jpg",
    "/project-gallery/interiors/bedroom3.jpg",
    "/project-gallery/interiors/diningroom1.jpg",
    "/project-gallery/interiors/diningroom10.jpg",
    "/project-gallery/interiors/diningroom2.jpg",
    "/project-gallery/interiors/diningroom3.jpg",
    "/project-gallery/interiors/diningroom4.jpg",
    "/project-gallery/interiors/diningroom5.jpg",
    "/project-gallery/interiors/diningroom6.jpg",
    "/project-gallery/interiors/diningroom7.jpg",
    "/project-gallery/interiors/diningroom8.jpg",
    "/project-gallery/interiors/diningroom9.jpg",
    "/project-gallery/interiors/finishingtouces3.jpg",
    "/project-gallery/interiors/finishingtouches1.jpg",
    "/project-gallery/interiors/finishingtouches2.jpg",
    "/project-gallery/interiors/finishingtouches4.jpg",
    "/project-gallery/interiors/homeeoffice1.jpg",
    "/project-gallery/interiors/homeoffice2.jpg",
    "/project-gallery/interiors/interior-1.jpg",
    "/project-gallery/interiors/interior-10.jpg",
    "/project-gallery/interiors/interior-11.jpg",
    "/project-gallery/interiors/interior-12.jpg",
    "/project-gallery/interiors/interior-13.jpg",
    "/project-gallery/interiors/interior-14.jpg",
    "/project-gallery/interiors/interior-15.jpg",
    "/project-gallery/interiors/interior-16.jpg",
    "/project-gallery/interiors/interior-17.jpg",
    "/project-gallery/interiors/interior-18.jpg",
    "/project-gallery/interiors/interior-19.jpg",
    "/project-gallery/interiors/interior-2.jpg",
    "/project-gallery/interiors/interior-20.jpg",
    "/project-gallery/interiors/interior-21.jpg",
    "/project-gallery/interiors/interior-22.jpg",
    "/project-gallery/interiors/interior-23.jpg",
    "/project-gallery/interiors/interior-24.jpg",
    "/project-gallery/interiors/interior-25.jpg",
    "/project-gallery/interiors/interior-26.jpg",
    "/project-gallery/interiors/interior-27.jpg",
    "/project-gallery/interiors/interior-28.jpg",
    "/project-gallery/interiors/interior-29.jpg",
    "/project-gallery/interiors/interior-3.jpg",
    "/project-gallery/interiors/interior-30.jpg",
    "/project-gallery/interiors/interior-31.jpg",
    "/project-gallery/interiors/interior-4.jpg",
    "/project-gallery/interiors/interior-5.jpg",
    "/project-gallery/interiors/interior-6.jpg",
    "/project-gallery/interiors/interior-7.jpg",
    "/project-gallery/interiors/interior-8.jpg",
    "/project-gallery/interiors/interior-9.jpg",
    "/project-gallery/interiors/livingroom10.jpg",
    "/project-gallery/interiors/livingroom11.jpg",
    "/project-gallery/interiors/livingroom12.jpg",
    "/project-gallery/interiors/livingroom3.jpg",
    "/project-gallery/interiors/livingroom4.jpg",
    "/project-gallery/interiors/livingroom5.jpg",
    "/project-gallery/interiors/livingroom6.jpg",
    "/project-gallery/interiors/livingroom7.jpg",
    "/project-gallery/interiors/livingroom8.jpg",
    "/project-gallery/interiors/livingroom9.jpg",
    "/project-gallery/interiors/livingroom-image1.jpg",
    "/project-gallery/interiors/livingroom-image2.jpg",
  ],
  "kitchen": [
    "/project-gallery/kitchen/kitchen1.jpg",
    "/project-gallery/kitchen/kitchen-1.jpg",
    "/project-gallery/kitchen/kitchen10.jpg",
    "/project-gallery/kitchen/kitchen-10.jpg",
    "/project-gallery/kitchen/kitchen11.jpg",
    "/project-gallery/kitchen/kitchen-11.jpg",
    "/project-gallery/kitchen/kitchen12.jpg",
    "/project-gallery/kitchen/kitchen-12.jpg",
    "/project-gallery/kitchen/kitchen13.jpg",
    "/project-gallery/kitchen/kitchen-13.jpg",
    "/project-gallery/kitchen/kitchen2.jpg",
    "/project-gallery/kitchen/kitchen-2.jpg",
    "/project-gallery/kitchen/kitchen3.jpg",
    "/project-gallery/kitchen/kitchen-3.jpg",
    "/project-gallery/kitchen/kitchen4.jpg",
    "/project-gallery/kitchen/kitchen-4.jpg",
    "/project-gallery/kitchen/kitchen5.jpg",
    "/project-gallery/kitchen/kitchen-5.jpg",
    "/project-gallery/kitchen/kitchen6.jpg",
    "/project-gallery/kitchen/kitchen-6.jpg",
    "/project-gallery/kitchen/kitchen7.jpg",
    "/project-gallery/kitchen/kitchen-7.jpg",
    "/project-gallery/kitchen/kitchen8.jpg",
    "/project-gallery/kitchen/kitchen-8.jpg",
    "/project-gallery/kitchen/kitchen9.jpg",
    "/project-gallery/kitchen/kitchen-9.jpg",
  ],
  "lake-cabin": [
    "/project-gallery/lake-cabin/lake-1.webp",
    "/project-gallery/lake-cabin/lake-2.jpg",
    "/project-gallery/lake-cabin/lake-3.jpg",
    "/project-gallery/lake-cabin/lake-4.jpg",
    "/project-gallery/lake-cabin/lake-5.jpg",
    "/project-gallery/lake-cabin/lake-6.webp",
    "/project-gallery/lake-cabin/lake-7.webp",
    "/project-gallery/lake-cabin/lake-8.jpg",
    "/project-gallery/lake-cabin/lakecabin.jpg",
    "/project-gallery/lake-cabin/lakefront1.webp",
    "/project-gallery/lake-cabin/lakefront2.avif",
    "/project-gallery/lake-cabin/lakefront2.jpg",
    "/project-gallery/lake-cabin/lakefront3.jpg",
    "/project-gallery/lake-cabin/lakefront4.jpg",
    "/project-gallery/lake-cabin/logcabin1.jpg",
    "/project-gallery/lake-cabin/logcabin2.webp",
    "/project-gallery/lake-cabin/logcabin3.webp",
  ],
  "roofing": [
    "/project-gallery/roofing/roffing-beforeandafter.jpg",
    "/project-gallery/roofing/roffing-beforeandafter2.jpg",
    "/project-gallery/roofing/roofing-1.jpg",
    "/project-gallery/roofing/roofing-2.jpg",
    "/project-gallery/roofing/roofing-3.jpg",
    "/project-gallery/roofing/roofing-4.jpg",
    "/project-gallery/roofing/roofing-5.jpg",
    "/project-gallery/roofing/roofing-beforeandafter3.jpg",
    "/project-gallery/roofing/roofing-beforeandafter4.jpg",
    "/project-gallery/roofing/roofing-beforeandafter5.jpg",
  ],
  "siding": [
    "/project-gallery/siding/siding-1.jpg",
    "/project-gallery/siding/siding-2.jpg",
    "/project-gallery/siding/siding-3.jpg",
    "/project-gallery/siding/siding-4.jpg",
    "/project-gallery/siding/siding-5.webp",
    "/project-gallery/siding/siding-6.webp",
    "/project-gallery/siding/siding-beforeandafter1.jpg",
    "/project-gallery/siding/siding-beforeandafter2.jpg",
    "/project-gallery/siding/siding-beforeandafter2.webp",
    "/project-gallery/siding/siding-beforeandafter3.webp",
    "/project-gallery/siding/siding-beforeandafter4.jpg",
    "/project-gallery/siding/siding-beforeandafter5.jpg",
  ],
  "windows-doors": [
    "/project-gallery/windows-doors/newdoorconstructionpic1.jpg",
    "/project-gallery/windows-doors/newwindowconstructionpic2.jpg",
    "/project-gallery/windows-doors/newwindowconstructionpic3.jpg",
    "/project-gallery/windows-doors/newwindowconstructionpic4.jpg",
    "/project-gallery/windows-doors/newwindowconstructionpics1.jpg",
    "/project-gallery/windows-doors/patiodoorconstructionpic1.jpg",
    "/project-gallery/windows-doors/patiodoorconstructionpic2.jpg",
    "/project-gallery/windows-doors/window-door-1.jpg",
    "/project-gallery/windows-doors/window-door-2.jpg",
    "/project-gallery/windows-doors/window-door-3.jpg",
    "/project-gallery/windows-doors/window-door-4.jpg",
    "/project-gallery/windows-doors/window-door-5.jpg",
    "/project-gallery/windows-doors/window-door-6.jpg",
    "/project-gallery/windows-doors/window-door-7.jpg",
  ],
} as const;

export type GalleryCategory = keyof typeof PROJECT_GALLERY;

export const SERVICE_GALLERY_MAP: Record<string, GalleryCategory[]> = {
  "kitchen-remodeling": ["kitchen", "cabinetry", "interiors"],
  "bathroom-remodeling": ["bathroom", "interiors"],
  "basement-finishing": ["interiors", "bathroom"],
  "decks-outdoor-living": ["deck", "docks", "lake-cabin"],
  "roofing": ["roofing"],
  "siding": ["siding", "windows-doors"],
  "custom-carpentry": ["cabinetry", "interiors"],
  "additions": ["additions", "lake-cabin", "windows-doors"],
  "garage-builds": ["additions", "interiors"],
};

const CATEGORY_ALIASES: Record<string, GalleryCategory> = {
  lake_cabin: "lake-cabin",
  windows_doors: "windows-doors",
};

export function galleryFor(
  category: GalleryCategory | string,
  limit = 9,
): string[] {
  const key = (CATEGORY_ALIASES[category] ?? category) as GalleryCategory;
  const images = PROJECT_GALLERY[key];
  if (!images) return [];
  return images.slice(0, limit);
}

export function galleryForService(slug: string, limit = 9): string[] {
  const categories = SERVICE_GALLERY_MAP[slug] ?? [];
  const images: string[] = [];
  for (const category of categories) {
    for (const image of PROJECT_GALLERY[category]) {
      if (images.length >= limit) return images;
      if (!images.includes(image)) images.push(image);
    }
  }
  return images;
}

export const HOME_GALLERY_PREVIEW = [
  ...PROJECT_GALLERY.kitchen.slice(0, 2),
  ...PROJECT_GALLERY.bathroom.slice(0, 1),
  ...PROJECT_GALLERY.deck.slice(0, 1),
  ...PROJECT_GALLERY.roofing.slice(0, 1),
  ...PROJECT_GALLERY["lake-cabin"].slice(0, 1),
  ...PROJECT_GALLERY.siding.slice(0, 1),
];

export const FEATURED_IMAGES = {
  kitchenHero: "/project-gallery/kitchen/kitchen7.jpg",
  kitchenDetail: "/project-gallery/kitchen/kitchen4.jpg",
  kitchenAccent: "/project-gallery/kitchen/kitchen9.jpg",
  bathroomHero: "/project-gallery/bathroom/bathroom5.jpg",
  bathroomDetail: "/project-gallery/bathroom/bathroom1.jpg",
  deckHero: "/project-gallery/deck/newdeckconstruction4.webp",
  deckDetail: "/project-gallery/deck/newdeckconstruction2.jpg",
  dockFeature: "/project-gallery/docks/customdock2.webp",
  lakeCabinHero: "/project-gallery/lake-cabin/lakecabin.jpg",
  lakeCabinDetail: "/project-gallery/lake-cabin/lakefront1.webp",
  roofingHero: "/project-gallery/roofing/roofing-beforeandafter4.jpg",
  roofingDetail: "/project-gallery/roofing/roffing-beforeandafter.jpg",
  sidingHero: "/project-gallery/siding/siding-beforeandafter2.jpg",
  sidingDetail: "/project-gallery/siding/siding-beforeandafter1.jpg",
  cabinetryHero: "/project-gallery/cabinetry/custom-cabinetry1.webp",
  cabinetryDetail: "/project-gallery/cabinetry/custom-cabinetry4.jpg",
  additionHero: "/project-gallery/additions/home-addtions3.jpg",
  additionDetail: "/project-gallery/additions/home-additions1.webp",
  commercialHero: "/project-gallery/interiors/homeeoffice1.jpg",
  commercialDetail: "/project-gallery/interiors/homeoffice2.jpg",
  livingRoomHero: "/project-gallery/interiors/livingroom11.jpg",
  contactHero: "/project-gallery/interiors/finishingtouches1.jpg",
  windowDoorFeature: "/project-gallery/windows-doors/newwindowconstructionpics1.jpg",
} as const;

export function photoList(paths: string[]) {
  return paths.map((image) => ({ image }));
}
